name: Cypress E2E testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  set_status:
    runs-on: ubuntu-latest
    steps:
      - name: set pending status
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GH_TOKEN}}
          context: 'E2E tests'
          description: 'Tests pending deploy'
          # success, error, failure, or pending
          state: 'pending'
          sha: ${{github.event.pull_request.head.sha}}

  trigger_e2e:
    name: Trigger E2E testing
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch E2E Testing
        run: |
          curl -XPOST -u "${{secrets.GH_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/taohuh/cypress-test-demo/dispatches --data '{"event_type": "on-demand-test", "client_payload": {"sha": "${{github.event.pull_request.head.sha}}"}}'
