name: Cypress E2E testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  set_status:
    runs-on: ubuntu-latest
    steps:
      - name: set pending status
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'E2E tests'
          description: 'Tests pending deploy'
          # success, error, failure, or pending
          state: 'pending'
          sha: ${{github.event.pull_request.head.sha}}

  trigger_e2e:
    name: Trigger E2E testing
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: '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'
          repository: taohuh/cypress-test-demo
          event-type: on-demand-test
      # - name: Dispatch E2E Testing
      #   run: |
      #     curl -X POST https://api.github.com/repos/taohuh/cypress-test-demo/dispatches \
      #     -H 'Accept: application/vnd.github.everest-preview+json' \
      #     -u ${{ secrets.GH_TOKEN }} \
      #     --data '{"event_type": "on-demand-test", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'